// Regenerates THIRD_PARTY_NOTICES.md: every Rust crate shipped for the Windows target (cargo-about,
// about.toml + about.hbs, local license files only) and the npm packages compiled into the UI
// bundle (found from a source-map build of the UI, with their own license files).
//
//   node scripts/gen-notices.mjs           write the file
//   node scripts/gen-notices.mjs --check   exit 1 if the file is out of date (CI, release gate)
//
// Needs cargo-about (`cargo install --locked cargo-about --features cli`) and `npm install`.
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "THIRD_PARTY_NOTICES.md");
const check = process.argv.includes("--check");

/** LF only and no trailing spaces, so the file is identical on every machine. */
const normalise = (text) =>
  text
    .replace(/\r\n?/g, "\n")
    .split("\n")
    .map((l) => l.trimEnd())
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim() + "\n";

function rustSection() {
  // cargo-about refuses to write to a redirected stdout under PowerShell: always use -o.
  const dir = mkdtempSync(join(tmpdir(), "mikyas-notices-"));
  try {
    const file = join(dir, "rust.md");
    execFileSync("cargo", ["about", "generate", "--offline", "--locked", "-o", file, "about.hbs"], {
      cwd: root,
      stdio: ["ignore", "inherit", "inherit"],
    });
    const out = readFileSync(file, "utf8");
    if (/\bmikyas/i.test(out)) throw new Error("our own crates must not be listed as third-party components");
    return out;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** npm packages whose code ends up in dist/, from the source maps of a throwaway build. */
function bundledPackages() {
  const dir = mkdtempSync(join(tmpdir(), "mikyas-notices-"));
  try {
    const vite = join(root, "node_modules", "vite", "bin", "vite.js");
    execFileSync(process.execPath, [vite, "build", "--sourcemap", "--outDir", dir, "--emptyOutDir", "--logLevel", "error"], {
      cwd: root,
      stdio: ["ignore", "ignore", "inherit"],
    });
    const found = new Set();
    const assets = join(dir, "assets");
    for (const f of readdirSync(assets).filter((f) => f.endsWith(".map"))) {
      for (const src of JSON.parse(readFileSync(join(assets, f), "utf8")).sources) {
        const m = src.replace(/\\/g, "/").match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
        if (m) found.add(m[1]);
      }
    }
    return [...found].sort();
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function npmSection(packages) {
  const parts = [];
  for (const name of packages) {
    const dir = join(root, "node_modules", ...name.split("/"));
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
    const files = readdirSync(dir)
      .filter((f) => /^(licen[cs]e|copying|notice)/i.test(f))
      .sort();
    if (files.length === 0) throw new Error(`${name}: no license file in node_modules`);
    const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url;
    parts.push(`### ${name} ${pkg.version} (${pkg.license})\n\n${repo ? `Source: ${repo.replace(/^git\+/, "")}\n\n` : ""}`);
    for (const f of files) {
      parts.push(`${f}:\n\n~~~~text\n${readFileSync(join(dir, f), "utf8").trim()}\n~~~~\n\n`);
    }
  }
  return parts.join("");
}

const header = `# Third-party notices

Mikyas — usage widget for Claude Code & Claude Desktop — is proprietary software (see
LICENSE), but it is built from open-source components. Their licenses are reproduced below, as
those licenses require. Nothing here changes the terms of Mikyas itself.

- **Rust crates** compiled into \`mikyas.exe\` and \`mikyas-capture.exe\` for Windows
  (x86_64-pc-windows-msvc), grouped by license text.
- **npm packages** compiled into the app's user interface.

Components under the Mozilla Public License 2.0 (MPL-2.0) are used unmodified; their source code
is available from crates.io (https://crates.io/crates/<name>) and from the repositories listed
below.

This file is generated by \`node scripts/gen-notices.mjs\`; do not edit it by hand.

## Rust crates

`;

const text = normalise(`${header}${rustSection()}\n## npm packages (user interface)\n\n${npmSection(bundledPackages())}`);

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== text) {
    console.error("THIRD_PARTY_NOTICES.md is out of date: run node scripts/gen-notices.mjs and commit it.");
    process.exit(1);
  }
  console.log("THIRD_PARTY_NOTICES.md is up to date.");
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT}`);
}
